# frozen_string_literal: true

load 'deploy'
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq
install_plugin Capistrano::Sidekiq::Systemd 
load 'deploy/assets'
load 'config/deploy' # remove this line to skip loading any of the default tasks
